# Generated by Django 4.1.2 on 2022-10-30 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50, verbose_name='Филиал')),
                ('adress', models.CharField(max_length=250, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='Название группы')),
                ('day', models.CharField(max_length=50, verbose_name='День недели когда занимается группа')),
                ('time', models.TimeField(verbose_name='Время занятия')),
                ('age', models.IntegerField(verbose_name='Возраст детей на занятии')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.branches', verbose_name='Филиал')),
            ],
        ),
        migrations.CreateModel(
            name='Coast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_abonem', models.CharField(max_length=50, verbose_name='Тип Абонемента')),
                ('coast', models.IntegerField(verbose_name='Цена Абонемента')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.branches', verbose_name='Филиал')),
            ],
        ),
    ]
